import { describe, test, expect } from "vitest";
import { convertPluginsJSToJSON } from "./jsToJSON";

describe("convertPluginsJSToJSON", () => {
  describe("old style input", () => {
    const expectedOutput = [
      "[",
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
      "]",
    ];

    test("removes comment lines from JS source", () => {
      const input = [
        "// Generated by RPG Maker.",
        "// Do not edit this file directly.",
        "var $plugins =",
        "[",
        `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
        `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
        "];",
      ];
      const result = convertPluginsJSToJSON(input.join("\n"));
      expect(result).toEqual(expectedOutput);
    });
    test("jsonParse", () => {
      const expected = [
        {
          name: "MockPlugin",
          status: true,
          description: "desc text",
          parameters: {},
        },
        {
          description: "test text",
          name: "TestPlugin",
          parameters: {},
          status: true,
        },
      ];
      const value = JSON.parse(expectedOutput.join("\n"));
      expect(value).toEqual(expected);
    });
  });
});
