// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"mockPlugin","status":true,"description":"テスト用の nameTable 付きプラグインです。","parameters":{"value":"0","nameTable":"{\"variableId\":\"0\",\"names\":\"[]\"}"}}
];
