import { describe, test, expect } from "vitest";
import { parsePluginParamRecord2 } from "./jsToJSON";
import type { PluginParamsRecord } from "./types";
import type {
  MessageOfparsePluginParamRecord,
  ResultOfparsePluginParamRecord,
} from "./types/result2";

const messages: MessageOfparsePluginParamRecord = {
  parseError: "Failed to parse JSON",
  notArray: "Parsed value is not an array",
  success: "Parsed successfully",
  partialSuccess: "Parsed with some invalid plugins",
};

const createSrc = (record: Partial<PluginParamsRecord>[]): string =>
  [
    "// Generated by RPG Maker.",
    "// Do not edit this file directly.",
    "var $plugins =",
    JSON.stringify(record, null, 2),
    ";",
  ].join("\n");

const testCaseFromInvalidRecord = (
  name: string,
  numInvalid: number,
  record: Partial<PluginParamsRecord>[],
): TestCase => ({
  name,
  src: createSrc(record),
  expected: {
    message: messages.partialSuccess,
    plugins: [],
    invalidPlugins: numInvalid,
  },
});

const testCaseFromRecord = (
  name: string,
  record: PluginParamsRecord[],
): TestCase => ({
  name,
  src: createSrc(record),
  expected: {
    message: messages.success,
    plugins: record,
    invalidPlugins: 0,
  },
});

interface TestCase {
  name: string;
  expected: ResultOfparsePluginParamRecord;
  src: string;
}

const runTestCase = (testCase: TestCase) => {
  test(testCase.name, () => {
    const result = parsePluginParamRecord2(testCase.src, messages);
    expect(result).toEqual(testCase.expected);
  });
};

const testCases: TestCase[] = [
  {
    name: "empty input",
    expected: {
      message: messages.success,
      plugins: [],
      invalidPlugins: 0,
    },
    src: "",
  },
  {
    name: "empty array input",
    expected: {
      message: messages.success,
      plugins: [],
      invalidPlugins: 0,
    },
    src: "[]",
  },
  {
    name: "valid input",
    expected: {
      invalidPlugins: 0,
      message: messages.success,
      plugins: [
        {
          name: "MockPlugin",
          status: true,
          description: "desc text",
          parameters: {},
        },
        {
          description: "test text",
          name: "TestPlugin",
          parameters: {},
          status: true,
        },
      ],
    },
    src: [
      "// Generated by RPG Maker.",
      "// Do not edit this file directly.",
      "var $plugins =",
      "[",
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
      "];",
    ].join("\n"),
  },
  {
    name: "invalid JSON input",
    expected: {
      message: messages.parseError,
      plugins: [],
      invalidPlugins: 0,
      error: expect.any(SyntaxError),
    },
    src: "{not a valid JSON",
  },
  {
    name: "input with one invalid plugin missing name",
    src: createSrc([
      {
        status: true,
        description: "A plugin missing name",
        parameters: {},
      },
      {
        name: "ValidPlugin",
        status: true,
        description: "A valid plugin",
        parameters: {},
      },
    ]),
    expected: {
      invalidPlugins: 1,
      message: messages.partialSuccess,
      plugins: [
        {
          name: "ValidPlugin",
          status: true,
          description: "A valid plugin",
          parameters: {},
        },
      ],
    },
  },
  testCaseFromRecord("input with empty", []),
  testCaseFromRecord("input with one valid plugin", [
    {
      name: "ValidPlugin",
      status: true,
      description: "A valid plugin",
      parameters: {},
    },
  ]),
  testCaseFromRecord("input with one valid plugin and disabled plugin", [
    {
      name: "ValidPlugin",
      status: true,
      description: "A valid plugin",
      parameters: {
        name: "bob",
        age: "20",
      },
    },
    {
      name: "disabled plugin",
      status: false,
      description: "A disabled plugin",
      parameters: {},
    },
  ]),
  testCaseFromInvalidRecord("input with one invalid plugin missing name", 1, [
    {
      status: true,
      description: "A plugin missing name",
      parameters: {},
    },
  ]),
];

describe("parsePluginParamRecord2", () => {
  testCases.forEach(runTestCase);
});
