import { describe, test, expect } from "vitest";
import { convertPluginsJSToJSON, parsePluginParamRecord } from "./jsToJSON";
import type { PluginParamsRecord } from "./types";

describe("convertPluginsJSToJSON", () => {
  describe("old style input", () => {
    const expectedOutput = [
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
    ];

    const input = [
      "// Generated by RPG Maker.",
      "// Do not edit this file directly.",
      "var $plugins =",
      "[",
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
      "];",
    ];
    test("removes comment lines from JS source", () => {
      const result = convertPluginsJSToJSON(input.join("\n"));
      expect(result).toEqual(expectedOutput);
    });
    const expectedValues: PluginParamsRecord[] = [
      {
        name: "MockPlugin",
        status: true,
        description: "desc text",
        parameters: {},
      },
      {
        description: "test text",
        name: "TestPlugin",
        parameters: {},
        status: true,
      },
    ];
    test("jsonParse", () => {
      const src = `[${expectedOutput.join("")}]`;
      const value = JSON.parse(src);
      expect(value).toEqual(expectedValues);
    });
    test("parsePluginParamObject", () => {
      const value = parsePluginParamRecord(input.join("\n"));
      expect(value).toEqual(expectedValues);
    });
  });
});
