import { describe, test, expect } from "vitest";
import { convertPluginsJSToJSON } from "./jsToJSON";

interface TestCase {
  name: string;
  input: string;
  expected: string[];
}
const runTestCase = (testCase: TestCase) => {
  test(testCase.name, () => {
    const result = convertPluginsJSToJSON(testCase.input);
    expect(result).toEqual(testCase.expected);
  });
};

const testCases: TestCase[] = [
  {
    name: "input with only comments and variable declaration",
    input: "aaa",
    expected: ["aaa"],
  },
  {
    name: "input with comments and variable declaration",
    input: ["//comment", "abc", "xyz", "//end"].join("\n"),
    expected: ["abc", "xyz"],
  },
  {
    name: "input with comments and variable declaration",
    input: [
      "// Generated by RPG Maker.",
      "// Do not edit this file directly.",
      "var $plugins =",
      "[",
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
      "];",
    ].join("\n"),
    expected: [
      `{"name":"MockPlugin","status":true,"description":"desc text","parameters":{}},`,
      `{"name":"TestPlugin","status":true,"description":"test text","parameters":{}}`,
    ],
  },
];

describe("convertPluginsJSToJSON", () => {
  testCases.forEach(runTestCase);
});
